### ISSUE TITLE
Test error with selenium-webdriver 2.48.0

### ISSUE THREAD

**Issue by marco-c** [marco-c/web-push#45]
```
undefined:1178

    vlog(2, () => this + ' scheduling notifications', this);

             ^

SyntaxError: Unexpected token )

    at goog.loadModuleFromSource_ (/home/travis/build/marco-c/web-push/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)

    at Object.goog.loadModule (/home/travis/build/marco-c/web-push/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)

    at /home/travis/build/marco-c/web-push/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6

    at Object.exports.runInContext (vm.js:64:17)

    at Object.Context.closure.goog.retrieveAndExecModule_ (/home/travis/build/marco-c/web-push/node_modules/selenium-webdriver/_base.js:135:8)

    at <anonymous>:1:6

    at Object.exports.runInContext (vm.js:64:17)

    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/home/travis/build/marco-c/web-push/node_modules/selenium-webdriver/_base.js:104:12)

    at Object.goog.importScript_ (/home/travis/build/marco-c/web-push/node_modules/selenium-webdriver/lib/goog/base.js:879:9)

    at Object.goog.importModule_ (/home/travis/build/marco-c/web-push/node_modules/selenium-webdriver/lib/goog/base.js:900:14)

npm ERR! Test failed.  See above for more details.
```

**Comment by marco-c** [comment]
Looks like since 2.48.0, selenium-webdriver needs Node.js to run with the "harmony" option (https://github.com/SeleniumHQ/selenium/commit/c42999ea6e71302313b2ed01ddd64c3bd3e6ffc5).
